services:
  jenkins:
    image: kaikfreitas/s07-jenkins:latest
    platform: linux/amd64
    container_name: s07-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/login" ]
      interval: 10s
      timeout: 5s
      retries: 5

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: s07-jenkins-agent
    user: root
    restart: unless-stopped
    environment:
      JENKINS_URL: http://jenkins:8080
      JENKINS_SECRET: ${AGENT_SECRET}
      JENKINS_AGENT_NAME: s07-jenkins-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins

  newman:
    build:
      context: .
      dockerfile: Dockerfile.newman
    container_name: s07-newman
    restart: unless-stopped
    volumes:
      - ./postman:/etc/newman

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: s07-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - jenkins

volumes:
  jenkins_data:
